databases:
  TRI:
    url: https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-plus-data-files-calendar-years-1987-present
    queries:
      TRI_year_reported: 'option'
      TRI_zip: 'value'
  RCRAInfo:
    url: https://rcrapublic.epa.gov/rcra-public-export/?outputType=CSV
    queries:
      Table_of_tables: "//table[@id='tables']"
  eGRID:
    url: https://www.epa.gov/egrid/emissions-generation-resource-integrated-database-egrid
    '2014':
        file_name: 'eGRID2014_Data_v2.xlsx'
        file_version: 'v2'
        download_url: 'https://www.epa.gov/sites/production/files/2020-01/egrid2018_historical_files_since_1996.zip'
    '2016':
        file_name: 'egrid2016_data.xlsx'
        file_version: ''
        download_url: 'https://www.epa.gov/sites/production/files/2020-01/egrid2018_historical_files_since_1996.zip'
    '2018':
        file_name: 'eGRID2018_Data_v2.xlsx'
        file_version: 'v2'
        download_url: 'https://www.epa.gov/sites/production/files/2020-03/egrid2018_data_v2.xlsx'
    '2019':
        file_name: 'eGRID2019_data.xlsx'
        file_version: ''
        download_url: 'https://www.epa.gov/sites/production/files/2021-02/egrid2019_data.xlsx'
  NEI:
    url: 'http://eis.epa.gov'
    '2011':
        file_name:
            - 'nei_2011_regions_1_thru_5.parquet'
            - 'nei_2011_regions_6_thru_10_and_other.parquet'
        file_version: 'v3'
    '2012':
        file_name:
            - 'sppd_rtr_17208.parquet'
            - 'sppd_rtr_17209.parquet'
        file_version: 'v1'
    '2013':
        file_name:
            - 'sppd_rtr_17198.parquet'
            - 'sppd_rtr_17207.parquet'
        file_version: 'v1'
    '2014':
        file_name:
            - 'nei_2014_regions_1_thru_5.parquet'
            - 'nei_2014_regions_6_thru_10_and_other.parquet'
        file_version: 'v2'
    '2015':
        file_name:
            - 'sppd_rtr_17021.parquet'
            - 'sppd_rtr_17197.parquet'
        file_version: 'v1'
    '2016':
        file_name:
            - 'sppd_rtr_16974.parquet'
            - 'sppd_rtr_16998.parquet'
        file_version: 'v1'
    '2017':
        file_name:
            - 'sppd_rtr_16940.parquet'
            - 'sppd_rtr_16958.parquet'
        file_version: 'v1'
    '2018':
        file_name:
            - 'sppd_rtr_16938.parquet'
            - 'sppd_rtr_16939.parquet'
        file_version: 'v1'
    national_url: 'https://gaftp.epa.gov/air/nei/__year__/data_summaries/__version___facility.zip'
    national_version:
        '2017': '2017v1/2017neiJan'
        '2014': '2014v2/2014neiv2'
        '2011': '2011v2/2011neiv2'
  DMR:
      url: 'https://echo.epa.gov/trends/loading-tool/water-pollution-search'
      base_url: 'https://echodata.epa.gov/echo/dmr_rest_services.get_custom_data_annual?'
      pollutant_list_url: 'https://echodata.epa.gov/echo/dmr_rest_services.get_loading_tool_params?output=csv'
      state_url: 'https://echodata.epa.gov/echo/dmr_rest_services.get_state_stats?p_year=__year__&output=csv'
  GHGRP:
      most_recent_year: '2020'
      enviro_url: 'https://data.epa.gov/efservice/'
      url: 'https://www.epa.gov/system/files/'
      data_summaries_url: 'other-files/2021-10/2020_data_summary_spreadsheets.zip'
        # Data Summary Spreadsheets: .zip file containing multi-year spreadsheets containing
        # the most important high-level information for facilities, as well as yearly
        # spreadsheets containing slightly more detailed information, including
        # reported emissions by greenhouse gas and process.
      esbb_subparts_url: 'documents/2021-10/e_s_cems_bb_cc_ll_full_data_set_10-06-2021.xlsx'
        # Subparts E, S-CEMS, BB, CC, LL Data Set: .xlsx file containing publicly available data
        # reported by facilities in the following industries across all reporting years:
        # Adipic Acid Production (E), Lime Manufacturing (S, CEMS reporters only),
        # Silicon Carbide Production (BB), Soda Ash Manufacturing (CC) and
        # Coal-based Liquid Fuel Suppliers (LL).
        # LL is not included because it is a supplier, rather than an emitter.
      lo_subparts_url: 'other-files/2021-10/l_o_freq_request_data_10_21.xlsx'
        # Subparts L, O Data Set: .xlsx file containing publicly available data
        # reported by facilities under:
        # Subpart L (Fluorinated Gas Production) and
        # Subpart O (HCFC-22 Production and HFC-23 Destruction)
        # across all reporting years.
      subpart_L_GWPs_url: 'https://ccdsupport.com/confluence/download/attachments/63996073/Subpart%20L%20Calculation%20Spreadsheet%20-%20Summarize%20Process%20Level%20CO2e%20by%20f-GHG.xls?version=1&modificationDate=1427459649000&api=v2'
      subpart_C_fuel_table: 'C_FUEL_LEVEL_INFORMATION'

